Polygon colliders on all clouds and meteor, beginning design
NullReferenceException: Object reference not set to an instance of an
object
GameCode.Update () (at Assets/Scripts/Game/GameCode.cs:62)